# Generated by Django 3.2.16 on 2023-02-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_alter_job_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
