# Generated by Django 3.2.16 on 2023-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
