# Generated by Django 3.2.16 on 2023-02-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230208_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.user'),
            preserve_default=False,
        ),
    ]
